---
abstract: 'Get video informations from Asg.to '
author:
  - 'Tatsuya Fukata C<< <tatsuya.fukata@gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::More: 0.80
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Asg
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 1.25
  DateTime::Format::ISO8601: 0.08
  DateTime::Format::Strptime: 1.5000
  Digest::MD5: 2.39
  Encode: 2.35
  HTML::TreeBuilder::XPath: 0.14
  LWP::UserAgent: 6.04
  URI: 1.59
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.05
